# approve_schedule.py
# Converts your approved candidate_schedule.csv into game/js/schedule.js

import pandas as pd
import json
from datetime import date

CSV_FILE      = "candidate_schedule.csv"
SCHEDULE_FILE = "game/js/schedule.js"

df = pd.read_csv(CSV_FILE)

# Filter to approved rows only
approved = df[df['approved'].str.strip().str.lower() == 'yes']
print(f"Approved days: {len(approved)} / {len(df)}")

# Build schedule entries
schedule = []
for _, row in approved.iterrows():
    card_ids = []
    for i in range(1, 9):
        cid = row.get(f'card_{i}_id', '')
        if pd.notna(cid) and cid:
            card_ids.append(str(cid).strip())
    
    if len(card_ids) == 8:
        schedule.append({
            'date':    str(row['date']).strip(),
            'cardIds': card_ids,
        })

# Sort by date
schedule.sort(key=lambda x: x['date'])

# Write schedule.js
js_content = f"""// schedule.js — GSSdle daily card sets
// Generated by approve_schedule.py on {date.today().isoformat()}
// DO NOT EDIT MANUALLY — regenerate using generate_schedule.py + approve_schedule.py

const SCHEDULE = {json.dumps(schedule, indent=2)};

// Get today's card set (Pacific time)
function getTodaySchedule() {{
  const now = new Date();
  const pacific = new Date(now.toLocaleString('en-US', {{ timeZone: 'America/Los_Angeles' }}));
  const today = pacific.toISOString().split('T')[0];
  return SCHEDULE.find(s => s.date === today) || null;
}}
"""

with open(SCHEDULE_FILE, 'w') as f:
    f.write(js_content)

print(f"✅ Saved {SCHEDULE_FILE} with {len(schedule)} days scheduled")
if schedule:
    print(f"   First: {schedule[0]['date']}")
    print(f"   Last:  {schedule[-1]['date']}")