// schedule.js
// Daily card sets for GSSdle
// Each entry: { date: "YYYY-MM-DD", cardIds: [...8 card IDs...] }
// Cards must be at least 2% apart from each other
// Generated by generate_schedule.py, curated manually

const SCHEDULE = [
  {
    date: "2026-03-21",
    cardIds: [
      "trust_2020s",
      "owngun_2020s",
      "divorce_2020s",
      "cappun_2020s",
      "abany_2020s",
      "grass_2020s",
      "fear_2020s",
      "colhomo_2020s"
    ]
  }
];

// Get today's card set (Pacific time)
function getTodaySchedule() {
  const now = new Date();
  // Convert to Pacific time
  const pacificOffset = getPacificOffset(now);
  const pacific = new Date(now.getTime() + pacificOffset * 60 * 60 * 1000);
  const today = pacific.toISOString().split('T')[0];
  return SCHEDULE.find(s => s.date === today) || null;
}

function getPacificOffset(date) {
  // Pacific is UTC-8 (PST) or UTC-7 (PDT)
  const jan = new Date(date.getFullYear(), 0, 1);
  const jul = new Date(date.getFullYear(), 6, 1);
  const stdOffset = Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset());
  const isDST = date.getTimezoneOffset() < stdOffset;
  return isDST ? -7 : -8;
}
