// schedule.js — GSSdle daily card sets
// Generated by approve_schedule.py on 2026-03-21
// DO NOT EDIT MANUALLY — regenerate using generate_schedule.py + approve_schedule.py

const SCHEDULE = [
  {
    "date": "2026-03-22",
    "cardIds": [
      "madat22_1990s",
      "memschl_1970s",
      "cohabit_1980s",
      "hyperten_2010s",
      "whypoor4_1990s",
      "absingleg_2020s",
      "hitchild_1980s",
      "sexeduc_1970s"
    ]
  },
  {
    "date": "2026-03-23",
    "cardIds": [
      "wkracism_2020s",
      "burglr_1970s",
      "wksups_2020s",
      "ticket_1970s",
      "cappun2_1970s",
      "draftcol_1980s",
      "healer_1980s",
      "reltruth_1990s"
    ]
  },
  {
    "date": "2026-03-24",
    "cardIds": [
      "volpol_1990s",
      "ethregion7_2020s",
      "wojob_1990s",
      "colhomo_1970s",
      "vote16_2010s",
      "racecen1_0022_2020s",
      "evwork_2010s",
      "babies_7222_2010s"
    ]
  },
  {
    "date": "2026-03-25",
    "cardIds": [
      "seefilm_1990s",
      "lookjob_2000s",
      "wksup_2020s",
      "wksup_2000s",
      "abhelp2_2020s",
      "wantjob2_1990s",
      "salsci_1970s",
      "evwork_2000s"
    ]
  },
  {
    "date": "2026-03-26",
    "cardIds": [
      "secondwk_2000s",
      "game12_2000s",
      "workless_2020s",
      "mcsds6_2010s",
      "rowngun_2010s",
      "abdefectg_2020s",
      "spkhomo_2000s",
      "prozac_1990s"
    ]
  },
  {
    "date": "2026-03-27",
    "cardIds": [
      "wkharoth_2020s",
      "mawkborn_1980s",
      "libmslm_2000s",
      "racdif3_1980s",
      "usintl_1990s",
      "genegoo2_2010s",
      "excelart_1990s",
      "courts_1980s"
    ]
  },
  {
    "date": "2026-03-28",
    "cardIds": [
      "whoelse1_2020s",
      "stockops_2000s",
      "evbrkdwn_2010s",
      "racteach_1970s",
      "forsteal_2000s",
      "courtsnv_2020s",
      "evwork_1980s",
      "hhrace_2010s"
    ]
  },
  {
    "date": "2026-03-29",
    "cardIds": [
      "memunion_2000s",
      "godoc_1990s",
      "racdif4_1970s",
      "divlawnv_2020s",
      "letdie1_2020s",
      "wksubs_2000s",
      "comphome_2000s",
      "ob911_1980s"
    ]
  },
  {
    "date": "2026-03-30",
    "cardIds": [
      "famper2_1990s",
      "pawrkslffam_2020s",
      "refxhour_1990s",
      "readfict_1990s",
      "wrkgrown_1980s",
      "hitrobbr_1970s",
      "regdocyr_2000s",
      "gunsdrnk_2000s"
    ]
  },
  {
    "date": "2026-03-31",
    "cardIds": [
      "whoelse3_2000s",
      "pistol_1970s",
      "empinput_2000s",
      "spkrac_1970s",
      "colath_2020s",
      "vote12_2010s",
      "chnang9_1990s",
      "chnang10_1990s"
    ]
  },
  {
    "date": "2026-04-01",
    "cardIds": [
      "strike_1970s",
      "pawrkslf_1970s",
      "colmil_1980s",
      "famgen_1990s",
      "conmedic_2010s",
      "febear_1970s",
      "verdict_2010s",
      "dangroth_2000s"
    ]
  },
  {
    "date": "2026-04-02",
    "cardIds": [
      "memvet_1980s",
      "webmob_2010s",
      "makeart_2000s",
      "emoteoth_1990s",
      "brass_1980s",
      "hapmar_1980s",
      "natenvir_1980s",
      "forgive3_1990s"
    ]
  },
  {
    "date": "2026-04-03",
    "cardIds": [
      "outofbiz_1990s",
      "ethregion20_2020s",
      "libmslmy_2020s",
      "rightref_1990s",
      "partteam_2020s",
      "hrsmoney_1990s",
      "knwpatnt_2000s",
      "preteen_7222_1990s"
    ]
  },
  {
    "date": "2026-04-04",
    "cardIds": [
      "live2_1990s",
      "suicide4_2020s",
      "racchng_1970s",
      "tax_2010s",
      "natheal_1970s",
      "natcrime_1980s",
      "postlf9_1980s",
      "xmarsex1_2000s"
    ]
  },
  {
    "date": "2026-04-05",
    "cardIds": [
      "givpol_1990s",
      "suicide4_2000s",
      "busing10_1980s",
      "relexp_2010s",
      "usintl_1970s",
      "febear_1990s",
      "selfhelp_1990s",
      "rprtst15_1990s"
    ]
  },
  {
    "date": "2026-04-06",
    "cardIds": [
      "memhobby_2000s",
      "depress_2010s",
      "libath_2000s",
      "wksups_2010s",
      "strredpg_2010s",
      "libcom_1970s",
      "natlart_1990s",
      "postlifev_2020s"
    ]
  },
  {
    "date": "2026-04-07",
    "cardIds": [
      "racmar_1980s",
      "pikupsex_1980s",
      "unemp_2020s",
      "trauma1_1990s",
      "partfull_2010s",
      "nataidy_1990s",
      "teens_1970s",
      "fearhome_1980s"
    ]
  },
  {
    "date": "2026-04-08",
    "cardIds": [
      "gomusic_2000s",
      "memchurh_1970s",
      "noathome_1990s",
      "helpful_1970s",
      "knwpatnt_2020s",
      "gunlaw_1990s",
      "knwblk_2000s",
      "aidssex_1980s"
    ]
  },
  {
    "date": "2026-04-09",
    "cardIds": [
      "wkageism_2020s",
      "wksup1_2010s",
      "anomia4_1970s",
      "pornlaw_1980s",
      "worknow_2000s",
      "erameans_1970s",
      "raceself_1990s",
      "hotcore_2010s"
    ]
  },
  {
    "date": "2026-04-10",
    "cardIds": [
      "arthrtis_2020s",
      "wrkgovt1_2020s",
      "fepol_2000s",
      "racmost_1990s",
      "natmass_2020s",
      "adpsy_2020s",
      "amenglsh_2000s",
      "natdiscm_2000s"
    ]
  },
  {
    "date": "2026-04-11",
    "cardIds": [
      "oth5_1990s",
      "memsport_1980s",
      "mustwork_2000s",
      "scimoral_1980s",
      "uscitzn_0822_2000s",
      "tablprce_1990s",
      "seemovie_1990s",
      "genejob_1990s"
    ]
  },
  {
    "date": "2026-04-12",
    "cardIds": [
      "burglr_1990s",
      "vetaid_1980s",
      "suicide2_2020s",
      "unemp_2000s",
      "trust_1980s",
      "spkrac_1980s",
      "if84who_1980s",
      "polhitok_2020s"
    ]
  },
  {
    "date": "2026-04-13",
    "cardIds": [
      "polmurdr_2000s",
      "polrally_1980s",
      "pawrkslf_2020s",
      "resdefwk_1980s",
      "lfehrdwk_1990s",
      "anomia7_1970s",
      "dwelown16_2010s",
      "ashamed_1990s"
    ]
  },
  {
    "date": "2026-04-14",
    "cardIds": [
      "memunion_1980s",
      "rifle_2020s",
      "pawrkslf_2010s",
      "hivkiss_2010s",
      "partteam_2010s",
      "quitsmk_1980s",
      "webmob_2020s",
      "babies_2020s"
    ]
  },
  {
    "date": "2026-04-15",
    "cardIds": [
      "suicide3_2000s",
      "racdif2_1980s",
      "relneg_2000s",
      "nateduc_1970s",
      "churhmem_1980s",
      "natmeet_2010s",
      "race_2010s",
      "evjob_2000s"
    ]
  },
  {
    "date": "2026-04-16",
    "cardIds": [
      "famper4_1990s",
      "switched_1980s",
      "life_2010s",
      "buyit12_2000s",
      "vote96_2000s",
      "abhelp1_2010s",
      "union_1980s",
      "babies_7222_2000s"
    ]
  },
  {
    "date": "2026-04-17",
    "cardIds": [
      "disabld1_2000s",
      "lockedup_2010s",
      "shotgun_2000s",
      "savesoul_2020s",
      "knwmhosp_1990s",
      "vote92_1990s",
      "wksubs1_2010s",
      "wrknokid_1990s"
    ]
  },
  {
    "date": "2026-04-18",
    "cardIds": [
      "fepolnv_2020s",
      "xmovie_1980s",
      "abhave3_1970s",
      "angrywrk_1990s",
      "libracy_2020s",
      "lawyer_1990s",
      "spkcomy_2020s",
      "numlangs_2010s"
    ]
  },
  {
    "date": "2026-04-19",
    "cardIds": [
      "suicide3g_2020s",
      "ethworld7_2020s",
      "rachome_1980s",
      "fear_1980s",
      "colmil_1990s",
      "petb4_2010s",
      "transair_1980s",
      "nataidy_2010s"
    ]
  },
  {
    "date": "2026-04-20",
    "cardIds": [
      "libhomo_2020s",
      "drama_2000s",
      "safetywk_2000s",
      "cowrkhlp_2020s",
      "pornlaw_2000s",
      "mhhired_2000s",
      "spevwork_2010s",
      "teens_7222_2010s"
    ]
  }
];

// Get today's card set (Pacific time)
function getTodaySchedule() {
  const now = new Date();
  const pacific = new Date(now.toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }));
  const today = pacific.toISOString().split('T')[0];
  return SCHEDULE.find(s => s.date === today) || null;
}
