// schedule.js — GSSdle daily card sets
// Generated by approve_schedule.py on 2026-04-07
// DO NOT EDIT MANUALLY — regenerate using generate_schedule.py + approve_schedule.py

const SCHEDULE = [
  {
    "date": "2026-04-08",
    "cardIds": [
      "law7_2000s",
      "gun_1970s",
      "whyjbend_1990s",
      "pafund_1980s",
      "chngeoth_2000s",
      "friend2_2000s",
      "eramamit_1970s",
      "abrape_2020s"
    ]
  },
  {
    "date": "2026-04-09",
    "cardIds": [
      "natcityy_1990s",
      "immcrime_1990s",
      "alloflfe_2000s",
      "sellorgn_1990s",
      "taxbylaw_2010s",
      "clsetown_2000s",
      "intenvir_2010s",
      "askcomp_2000s"
    ]
  },
  {
    "date": "2026-04-10",
    "cardIds": [
      "ethregion24_2020s",
      "memother_2000s",
      "txpol_2000s",
      "intltest_1990s",
      "infnettv_1990s",
      "imprveat_2020s",
      "polaryr3_2000s",
      "confinan_1980s"
    ]
  },
  {
    "date": "2026-04-11",
    "cardIds": [
      "educemp_1980s",
      "grnsol_2020s",
      "colrac_1980s",
      "premarsx_1970s",
      "natcrime_2000s",
      "mentlill_2000s",
      "webmob_2020s",
      "aidcol_1990s"
    ]
  },
  {
    "date": "2026-04-12",
    "cardIds": [
      "mhresoth_2000s",
      "wait2_2000s",
      "imports_2000s",
      "ilikejob_1980s",
      "king_1980s",
      "askforgn_1990s",
      "comprend_2010s",
      "wkfreedm_2000s"
    ]
  },
  {
    "date": "2026-04-13",
    "cardIds": [
      "getmar_2000s",
      "timeleis_2000s",
      "usangry_1990s",
      "attend12_2010s",
      "crimhold_1990s",
      "big5d2_2000s",
      "marlegit_2000s",
      "secmilop_1990s"
    ]
  },
  {
    "date": "2026-04-14",
    "cardIds": [
      "hrdshp1_1990s",
      "spunemp_1990s",
      "compwage_2000s",
      "supervis_2010s",
      "doc10_1990s",
      "payeduc_1990s",
      "emfamloc_2000s",
      "mhsecret_2000s"
    ]
  },
  {
    "date": "2026-04-15",
    "cardIds": [
      "modeorg_2020s",
      "freemns2_2000s",
      "toodifme_2010s",
      "libmslm_2010s",
      "medsavtx_2000s",
      "welfare4_1980s",
      "obeylaws_2010s",
      "mhsocial_2000s"
    ]
  },
  {
    "date": "2026-04-16",
    "cardIds": [
      "feelhsps_2000s",
      "reg16_7222_2020s",
      "abmoral_2010s",
      "forland_2020s",
      "abpoor_1980s",
      "aidunemp_1990s",
      "fehome_1980s",
      "alike1_1990s"
    ]
  },
  {
    "date": "2026-04-17",
    "cardIds": [
      "meeting_2000s",
      "fehelp_1990s",
      "ethsame_2000s",
      "credchoice_2020s",
      "suicide1_1970s",
      "treat7_2000s",
      "spkcom_1980s",
      "wkfreedm_2010s"
    ]
  },
  {
    "date": "2026-04-18",
    "cardIds": [
      "screlig_2000s",
      "joblose_1970s",
      "reborn_2020s",
      "webmob_2010s",
      "volchrty_2010s",
      "marsame1_2010s",
      "natspac_2020s",
      "lookaway_2000s"
    ]
  },
  {
    "date": "2026-04-19",
    "cardIds": [
      "hurtatwk_2020s",
      "depress_2010s",
      "reg16_7222_1980s",
      "hlthmore_2020s",
      "taxshare_1980s",
      "racchng_1980s",
      "raclive_2000s",
      "drink_1970s"
    ]
  },
  {
    "date": "2026-04-20",
    "cardIds": [
      "raceacs12_2020s",
      "memfrat_2000s",
      "stress_1990s",
      "pawrkslf_1980s",
      "jobmeans_1990s",
      "taxpoor_2000s",
      "racclos_1970s",
      "intecon_2010s"
    ]
  },
  {
    "date": "2026-04-21",
    "cardIds": [
      "evmhp_1990s",
      "grngroup_1990s",
      "suicide2_2020s",
      "imppol_1980s",
      "grnprice_2000s",
      "maborn_2020s",
      "racpres_2000s",
      "racpres_2010s"
    ]
  },
  {
    "date": "2026-04-22",
    "cardIds": [
      "madeg_1990s",
      "sparms_1990s",
      "proz1_2000s",
      "bible_2000s",
      "world4_1980s",
      "blnumok_1980s",
      "rimpskls_2000s",
      "famdif16_1970s"
    ]
  },
  {
    "date": "2026-04-23",
    "cardIds": [
      "flickr_2010s",
      "fatalism_1990s",
      "discwhy2_1990s",
      "earnshh_2010s",
      "life_2020s",
      "grprelig_2000s",
      "closewht_2000s",
      "aidunemp_2010s"
    ]
  },
  {
    "date": "2026-04-24",
    "cardIds": [
      "jobinc_1970s",
      "usedup_2000s",
      "relsprt2_2000s",
      "wrkslffam_2010s",
      "wantjob2_2010s",
      "vote68_1970s",
      "cowrksta_2020s",
      "jobkeep_1980s"
    ]
  },
  {
    "date": "2026-04-25",
    "cardIds": [
      "ethregion94_2020s",
      "unrespct_1980s",
      "anomia7_1990s",
      "fechld_2010s",
      "privgovt_1990s",
      "wrknokid_1990s",
      "redeemer_1980s",
      "natrelax_2010s"
    ]
  },
  {
    "date": "2026-04-26",
    "cardIds": [
      "ethregion72_2020s",
      "intnews_2020s",
      "pinterst_2010s",
      "equal5_1980s",
      "mawork14_2000s",
      "wlthhsps_1990s",
      "carecost_2010s",
      "hlthplan_2000s"
    ]
  },
  {
    "date": "2026-04-27",
    "cardIds": [
      "fringe7_1990s",
      "wordh_1980s",
      "racdif1x_2020s",
      "pres96_2000s",
      "movenei_1990s",
      "enjoynat_2020s",
      "abhlth_1990s",
      "mhtreatd_2020s"
    ]
  },
  {
    "date": "2026-04-28",
    "cardIds": [
      "othjew_2010s",
      "hlth6_1990s",
      "limitedp_2000s",
      "attend_2000s",
      "unemp_1990s",
      "racpromo_1990s",
      "theism_2000s",
      "class_2020s"
    ]
  },
  {
    "date": "2026-04-29",
    "cardIds": [
      "grndemo_2010s",
      "earnmore_1990s",
      "ashamed_2020s",
      "contpoor_2020s",
      "life_1980s",
      "hlthsat_2020s",
      "inuitway_2010s",
      "sexeduc_2000s"
    ]
  },
  {
    "date": "2026-04-30",
    "cardIds": [
      "finan3_2000s",
      "racdif2_2000s",
      "livnowed_1990s",
      "letters_2000s",
      "natrace_1980s",
      "jewscls_2000s",
      "hlthinf_2020s",
      "ferespct_2000s"
    ]
  },
  {
    "date": "2026-05-01",
    "cardIds": [
      "memunion_2000s",
      "advisor4_2000s",
      "depress_2020s",
      "trust_2010s",
      "watergen_1990s",
      "natchld_2000s",
      "forgive1_1990s",
      "numkids_2010s"
    ]
  },
  {
    "date": "2026-05-02",
    "cardIds": [
      "preteen_7222_2000s",
      "feless1_1990s",
      "cope4_1990s",
      "carprivt_1990s",
      "chldidel_1970s",
      "kid5up_1990s",
      "spkhomo_1970s",
      "polescap_1980s"
    ]
  },
  {
    "date": "2026-05-03",
    "cardIds": [
      "raceacs9_2020s",
      "intlhsps_2010s",
      "abmoral_2020s",
      "punsin_2000s",
      "influhsp_1990s",
      "knwmhosp_2000s",
      "jobaff_1990s",
      "jobsecok_2000s"
    ]
  },
  {
    "date": "2026-05-04",
    "cardIds": [
      "pig_2010s",
      "laidoff_2020s",
      "padeg_1970s",
      "conchurh_1990s",
      "txeco_2010s",
      "natspacy_2020s",
      "trusty_1980s",
      "viglab06_2000s"
    ]
  },
  {
    "date": "2026-05-05",
    "cardIds": [
      "volhlth_1990s",
      "psyckid2_1990s",
      "poleff15_1990s",
      "occmobil_1980s",
      "abnomore_2020s",
      "asnjobs_1990s",
      "spwrksch_2000s",
      "abhave2_1970s"
    ]
  },
  {
    "date": "2026-05-06",
    "cardIds": [
      "hlth8_1990s",
      "worryjob_2000s",
      "privent_2020s",
      "abany_1970s",
      "chemgen1_2020s",
      "amgovt_1990s",
      "natcrime_2020s",
      "spvtrfair_2010s"
    ]
  },
  {
    "date": "2026-05-07",
    "cardIds": [
      "smokecig_1970s",
      "evsmoke_1990s",
      "hlthmntl_2010s",
      "recycle_2020s",
      "faith3_1980s",
      "sbwork2_1990s",
      "firstyou_2000s",
      "pawrkgrw_2020s"
    ]
  }
];

// Get today's card set (Pacific time)
function getTodaySchedule() {
  const now = new Date();
  const pacific = new Date(now.toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }));
  const today = pacific.toISOString().split('T')[0];
  return SCHEDULE.find(s => s.date === today) || null;
}
